server:
  port: 8328
spring:
#file size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
           
# oracle connect
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: S20230501
    password: tiger
    driver-class-name: oracle.jdbc.driver.OracleDriver
  
# jpa setting
  jpa:
    hibernate:
      ddl-auto: none #none create
    properties:
      hibernate:
        default_batch_fetch_size : 500
      show_sql: true       #sout에 어떤 sql 실행되는거 보여줌
      format_sql: true

# viewResolover
  mvc:
   view:
    prefix: /WEB-INF/views/
    suffix: .jsp

# MyBatis, classpath = resource폴더임.
mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml
        

    